name: 🚀 Secure Angular Deploy with Firebase
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: 🔐 Inject Firebase Secrets
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.prod.ts <<EOF
          export const environment = {
            production: true,
            firebase: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}'
            }
          };
          EOF
          grep "production:" src/environments/environment.prod.ts

      - name: 📌 Install Dependencies
        run: npm ci

      - name: 🏗️ Build Angular App
        run: npm run build -- --configuration production
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: 🐛 Verificar Build Output
        run: |
          echo "Build directory contents:"
          ls -la dist/cla/browser
          echo "Checking for Firebase config in main.js:"
          grep -o "apiKey" dist/cla/browser/main.js || echo "No API key found in build"

      - name: 🧹 Secure Clean & Deploy via WebDAV
        env:
          WEBDISK_USERNAME: ${{ secrets.WEBDISK_USERNAME }}
          WEBDISK_PASSWORD: ${{ secrets.WEBDISK_PASSWORD }}
        run: |
          BUILD_DIR="dist/cla/browser"
          WEBDISK_URL="https://cla-cg.org:2078"
          PROTECTED_ITEMS=( "drive" "admin" )

          echo "🔐 Testing WebDAV connection..."
          curl -u $WEBDISK_USERNAME:$WEBDISK_PASSWORD -X PROPFIND $WEBDISK_URL/ --fail --silent --show-error >/dev/null

          sudo apt-get update && sudo apt-get install -y xmlstarlet

          echo "📡 Fetching remote file list..."
          REMOTE_ITEMS=$(curl -u $WEBDISK_USERNAME:$WEBDISK_PASSWORD -X PROPFIND $WEBDISK_URL/ --silent | \
            xmlstarlet sel -t -v "//a:href" -n | sed "s|$WEBDISK_URL||" | sed 's|^/||' | grep -v '^$' | sort -ur)

          echo "🧹 Cleaning remote server..."
          for item in $REMOTE_ITEMS; do
            [[ -z "$item" ]] && continue
            protected=false
            for p in "${PROTECTED_ITEMS[@]}"; do
              [[ "$item" == "$p"* ]] && protected=true && break
            done
            if [ "$protected" = false ]; then
              echo "🗑️ Deleting: $item"
              curl -u $WEBDISK_USERNAME:$WEBDISK_PASSWORD -X DELETE "$WEBDISK_URL/$item" --silent --show-error || true
            else
              echo "🛡️ Preserving: $item"
            fi
          done

          echo "🚀 Uploading build..."
          find $BUILD_DIR -type f | while read -r file; do
            remote_path="${file#$BUILD_DIR/}"
            remote_dir=$(dirname "$remote_path")

            if [ "$remote_dir" != "." ]; then
              curl -u $WEBDISK_USERNAME:$WEBDISK_PASSWORD -X MKCOL "$WEBDISK_URL/$remote_dir" --silent --show-error || true
            fi

            for attempt in {1..3}; do
              if curl -u $WEBDISK_USERNAME:$WEBDISK_PASSWORD -T "$file" -X PUT "$WEBDISK_URL/$remote_path" --silent --show-error; then
                echo "✅ Uploaded: $remote_path"
                break
              elif [[ $attempt -eq 3 ]]; then
                echo "❌ Failed to upload: $remote_path"
                exit 1
              else
                sleep $((attempt * 2))
              fi
            done
          done

          echo "🎉 Deployment completed successfully!"
          echo "🌐 Live at: https://cla-cg.org"
